import type { Channel, InventoryItem, User } from "@/lib/types";

export const currentUser: User = {
  id: 'user-1',
  name: 'Alex Chen',
  role: 'Student',
  avatarUrl: 'https://picsum.photos/seed/user-alex/40/40',
};

export const channels: Channel[] = [
  {
    id: "computer-lab-1",
    name: "#computer-lab-1",
    description: "Basic computer and electronics kits",
  },
  {
    id: "computer-lab-2",
    name: "#computer-lab-2",
    description: "Advanced micro-controllers and IoT",
  },
  {
    id: "chemistry-lab-1",
    name: "#chemistry-lab-1",
    description: "General chemistry equipment",
  },
  {
    id: "robotics-lab-1",
    name: "#robotics-lab-1",
    description: "Robotics components and kits",
  },
  {
    id: "robotics-lab-2",
    name: "#robotics-lab-2",
    description: "Large mechanical and fabrication equipment",
  },
];

export const items: InventoryItem[] = [
  {
    id: "item-13",
    name: "High-Performance Desktop PC",
    description: "For intensive computing tasks.",
    channelId: "computer-lab-1",
    status: "Available",
    imageUrl: "https://picsum.photos/seed/desktop-pc/600/400",
    imageHint: "desktop computer",
  },
  {
    id: "item-14",
    name: "VR Headset Kit",
    description: "Immersive virtual reality experience.",
    channelId: "computer-lab-1",
    status: "Available",
    imageUrl: "https://picsum.photos/seed/vr-headset/600/400",
    imageHint: "vr headset",
  },
  {
    id: "item-1",
    name: "Arduino Starter Kit",
    description: "Complete starter kit for learning Arduino.",
    channelId: "computer-lab-1",
    status: "Locked",
    imageUrl: "https://picsum.photos/seed/arduino-kit/600/400",
    imageHint: "arduino kit",
  },
  {
    id: "item-15",
    name: "Network Switch",
    description: "24-port Gigabit network switch.",
    channelId: "computer-lab-1",
    status: "Locked",
    imageUrl: "https://picsum.photos/seed/network-switch/600/400",
    imageHint: "network switch",
  },
  {
    id: "item-2",
    name: "Raspberry Pi 4 Kit",
    description: "8GB RAM model with case, power supply, and fan.",
    channelId: "computer-lab-2",
    status: "Locked",
    imageUrl: "https://picsum.photos/seed/rpi4/600/400",
    imageHint: "raspberry pi",
  },
  {
    id: "item-3",
    name: "Sensor Pack",
    description: "A variety of sensors for electronics projects.",
    channelId: "computer-lab-2",
    status: "Available",
    imageUrl: "https://picsum.photos/seed/sensors/600/400",
    imageHint: "electronic sensors",
  },
  {
    id: "item-4",
    name: "ESP32 Development Board",
    description: "WiFi and Bluetooth enabled microcontroller.",
    channelId: "computer-lab-2",
    status: "Available",
    imageUrl: "https://picsum.photos/seed/esp32/600/400",
    imageHint: "circuit board",
  },
    {
    id: "item-12",
    name: "FPGA Development Kit",
    description: "Field-Programmable Gate Array for custom logic circuits.",
    channelId: "computer-lab-2",
    status: "Locked",
    imageUrl: "https://picsum.photos/seed/fpga/600/400",
    imageHint: "circuit board",
  },
  {
    id: "item-5",
    name: "Beaker Set",
    description: "Set of 5 glass beakers, various sizes.",
    channelId: "chemistry-lab-1",
    status: "Available",
    imageUrl: "https://picsum.photos/seed/beakers/600/400",
    imageHint: "lab beakers",
  },
  {
    id: "item-6",
    name: "Digital Scale",
    description: "High-precision digital scale (0.01g).",
    channelId: "chemistry-lab-1",
    status: "Borrowed",
    imageUrl: "https://picsum.photos/seed/scale/600/400",
    imageHint: "digital scale",
  },
  {
    id: "item-7",
    name: "Bunsen Burner",
    description: "Standard laboratory Bunsen burner.",
    channelId: "chemistry-lab-1",
    status: "Locked",
    imageUrl: "https://picsum.photos/seed/burner/600/400",
    imageHint: "bunsen burner",
  },
  {
    id: "item-8",
    name: "Servo Motor Pack",
    description: "Pack of 10 micro servos for robotics.",
    channelId: "robotics-lab-1",
    status: "Available",
    imageUrl: "https://picsum.photos/seed/servos/600/400",
    imageHint: "servo motors",
  },
  {
    id: "item-9",
    name: "Robot Chassis Kit",
    description: "4WD robot car chassis with motors and wheels.",
    channelId: "robotics-lab-1",
    status: "Available",
    imageUrl: "https://picsum.photos/seed/chassis/600/400",
    imageHint: "robot chassis",
  },
  {
    id: "item-10",
    name: "CNC Milling Machine",
    description: "Small desktop CNC for soft metals and plastics.",
    channelId: "robotics-lab-2",
    status: "Locked",
    imageUrl: "https://picsum.photos/seed/cnc/600/400",
    imageHint: "milling machine",
  },
  {
    id: "item-11",
    name: "3D Printer",
    description: "FDM 3D printer with a 20x20x20cm build volume.",
    channelId: "robotics-lab-2",
    status: "Borrowed",
    imageUrl: "https://picsum.photos/seed/3d-printer/600/400",
    imageHint: "3d printer",
  },
];
