import type { Channel, InventoryItem, User, BorrowHistory } from "@/lib/types";

export const currentUser: User = {
  id: 'user-1',
  name: 'Arnie Jabonero',
  role: 'Student',
  avatarUrl: 'https://i.pinimg.com/736x/38/43/d4/3843d494d3ecb871de072528e60d06a8.jpg',
  // Student Fields
  idNumber: '2021-01234',
  year: '3rd Year',
  grade: '1.75',
  course: 'BS in Computer Science',
  // Teacher/Staff/Admin Fields
  department: 'College of Computer Studies',
  employeeId: 'EMP-98765',
};

export const channels: Channel[] = [
  {
    id: "computer-lab-1",
    name: "#computer-lab-1",
    description: "Basic computer and electronics kits",
  },
  {
    id: "computer-lab-2",
    name: "#computer-lab-2",
    description: "Advanced micro-controllers and IoT",
  },
  {
    id: "chemistry-lab-1",
    name: "#chemistry-lab-1",
    description: "General chemistry equipment",
  },
  {
    id: "robotics-lab-1",
    name: "#robotics-lab-1",
    description: "Robotics components and kits",
  },
  {
    id: "robotics-lab-2",
    name: "#robotics-lab-2",
    description: "Large mechanical and fabrication equipment",
  },
];

export const items: InventoryItem[] = [
  {
    id: "item-13",
    name: "High-Performance Desktop PC",
    description: "For intensive computing tasks.",
    channelId: "computer-lab-1",
    status: "Available",
    imageUrl: "https://cdn.shopify.com/s/files/1/0632/2244/8205/files/AMD-Elite-10-scaled_1a0b6d95-5a74-49a2-9c59-2a026b0ebd4c.webp?v=1758667214",
    imageHint: "desktop computer",
    quantity: 5,
  },
  {
    id: "item-14",
    name: "VR Headset Kit",
    description: "Immersive virtual reality experience.",
    channelId: "computer-lab-1",
    status: "Available",
    imageUrl: "https://i.pinimg.com/736x/91/27/50/912750b850b7a994e567850d4cf03b27.jpg",
    imageHint: "vr headset",
    quantity: 3,
  },
  {
    id: "item-1",
    name: "Arduino Starter Kit",
    description: "Complete starter kit for learning Arduino.",
    channelId: "computer-lab-1",
    status: "Locked",
    imageUrl: "https://i.pinimg.com/736x/37/92/c1/3792c10fc5742c0f79e479e4283535b1.jpg",
    imageHint: "arduino kit",
    quantity: 15,
  },
  {
    id: "item-15",
    name: "Network Switch",
    description: "24-port Gigabit network switch.",
    channelId: "computer-lab-1",
    status: "Locked",
    imageUrl: "https://i.pinimg.com/736x/07/da/fe/07dafe714c44fe790151d85f2f8c1640.jpg",
    imageHint: "network switch",
    quantity: 4,
  },
  {
    id: "item-2",
    name: "Raspberry Pi 4 Kit",
    description: "8GB RAM model with case, power supply, and fan.",
    channelId: "computer-lab-2",
    status: "Locked",
    imageUrl: "https://i.pinimg.com/736x/d0/c9/50/d0c950a1a18f6d6b4ac1b8fb4905ade0.jpg",
    imageHint: "raspberry pi",
    quantity: 10,
  },
  {
    id: "item-3",
    name: "Sensor Pack",
    description: "A variety of sensors for electronics projects.",
    channelId: "computer-lab-2",
    status: "Available",
    imageUrl: "https://i.pinimg.com/736x/a2/4f/dd/a24fdd87f603a7b41460e8937b7959a4.jpg",
    imageHint: "electronic sensors",
    quantity: 25,
  },
  {
    id: "item-4",
    name: "ESP32 Development Board",
    description: "WiFi and Bluetooth enabled microcontroller.",
    channelId: "computer-lab-2",
    status: "Available",
    imageUrl: "https://i.pinimg.com/736x/c5/a5/4f/c5a54f44ad57ac58a9e5b3d8823c2f2e.jpg",
    imageHint: "circuit board",
    quantity: 30,
  },
    {
    id: "item-12",
    name: "FPGA Development Kit",
    description: "Field-Programmable Gate Array for custom logic circuits.",
    channelId: "computer-lab-2",
    status: "Locked",
    imageUrl: "https://i.pinimg.com/736x/a6/ee/09/a6ee09ccd158b733cc8ee46fdebe0289.jpg",
    imageHint: "circuit board",
    quantity: 8,
  },
  {
    id: "item-5",
    name: "Beaker Set",
    description: "Set of 5 glass beakers, various sizes.",
    channelId: "chemistry-lab-1",
    status: "Available",
    imageUrl: "https://i.pinimg.com/736x/2f/69/34/2f69342ae9d36ff40e26b8ce7ced4f04.jpg",
    imageHint: "lab beakers",
    quantity: 20,
  },
  {
    id: "item-6",
    name: "Digital Scale",
    description: "High-precision digital scale (0.01g).",
    channelId: "chemistry-lab-1",
    status: "Active",
    imageUrl: "https://i.pinimg.com/736x/be/c7/24/bec72421f24deda6ed0b771e530022e0.jpg",
    imageHint: "digital scale",
    quantity: 1,
  },
  {
    id: "item-7",
    name: "Bunsen Burner",
    description: "Standard laboratory Bunsen burner.",
    channelId: "chemistry-lab-1",
    status: "Locked",
    imageUrl: "https://i.pinimg.com/736x/04/c8/11/04c811881ecaaeb142c4f5c1e909b9b2.jpg",
    imageHint: "bunsen burner",
    quantity: 12,
  },
  {
    id: "item-8",
    name: "Servo Motor Pack",
    description: "Pack of 10 micro servos for robotics.",
    channelId: "robotics-lab-1",
    status: "Available",
    imageUrl: "https://picsum.photos/seed/servos/600/400",
    imageHint: "servo motors",
    quantity: 18,
  },
  {
    id: "item-9",
    name: "Robot Chassis Kit",
    description: "4WD robot car chassis with motors and wheels.",
    channelId: "robotics-lab-1",
    status: "Available",
    imageUrl: "https://picsum.photos/seed/chassis/600/400",
    imageHint: "robot chassis",
    quantity: 15,
  },
  {
    id: "item-10",
    name: "CNC Milling Machine",
    description: "Small desktop CNC for soft metals and plastics.",
    channelId: "robotics-lab-2",
    status: "Locked",
    imageUrl: "https://picsum.photos/seed/cnc/600/400",
    imageHint: "milling machine",
    quantity: 2,
  },
  {
    id: "item-11",
    name: "3D Printer",
    description: "FDM 3D printer with a 20x20x20cm build volume.",
    channelId: "robotics-lab-2",
    status: "Borrowed",
    imageUrl: "https://picsum.photos/seed/3d-printer/600/400",
    imageHint: "3d printer",
    quantity: 3,
  },
];

export const borrowHistory: BorrowHistory[] = [
    { id: 'bh1', studentName: 'Alex Doe', itemName: 'Arduino Starter Kit', date: '2024-07-28', status: 'Returned' },
    { id: 'bh2', studentName: 'Jane Smith', itemName: 'Bunsen Burner', date: '2024-07-27', status: 'Denied' },
    { id: 'bh3', studentName: 'Sam Wilson', itemName: 'FPGA Development Kit', date: '2024-07-29', status: 'Approved' },
    { id: 'bh4', studentName: 'Casey Jones', itemName: '3D Printer', date: '2024-07-29', status: 'Active' },
    { id: 'bh5', studentName: 'Alex Doe', itemName: 'CNC Milling Machine', date: '2024-07-30', status: 'Pending' },
    { id: 'bh6', studentName: 'Maria Garcia', itemName: 'Network Switch', date: '2024-07-30', status: 'Approved' },
    { id: 'bh7', studentName: 'Sam Wilson', itemName: 'Raspberry Pi 4 Kit', date: '2024-07-25', status: 'Returned' },
    { id: 'bh8', studentName: 'John Appleseed', itemName: 'Digital Scale', date: '2024-07-31', status: 'Active'},
];
